"""deconvolution — 2-D image deblurring with Gaussian / motion / disk PSFs.

Recover a non-negative image ``x`` from ``y = k ∗ x + n`` (Gaussian noise) or
``y ~ Poisson(peak · (k ∗ x) + background)`` (photon counts). The forward operator is a
zero-padded (non-periodic) :class:`~nefi.operators.FFTConvolution` whose PSF is a *function of the
grid spacing*, so it is rebuilt consistently at every curriculum resolution. Data are generated by
the same physics on a 2× finer grid in float64 and area-averaged onto the detector grid
(``fidelity_tag="blur-2x-float64"``, inverse-crime guard). The prior is a coordinate neural field
with a non-negative head (``Softplus`` or ``Bounded(0, 1)``) plus isotropic TV (NeFTY Eq. 22),
solved with the NeTMY two-stage multiscale curriculum (Tab. 6).

Baselines: ``grid`` (free pixels, Tikhonov/Grid-Opt style), ``deep_decoder``, ``gaussian_splat``
(designed for ``sparse_dots``), ``admm`` (grid + ℓ1/box ADMM) and the closed-form ``wiener``
filter (:func:`wiener`).
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import torch

from ...baselines import baseline_problem
from ...bench.base import DataGenerator, SceneGenerator
from ...domain import Domain
from ...errors import ConfigError
from ...fields import Bounded, GridField, Heads, Identity, NeuralField, Softplus
from ...losses import L1, MSE, TV, LossSet, PoissonNLL, Tikhonov
from ...measurement import Measurement
from ...metrics.basic import mse, psnr, ssim
from ...operators.base import Nuisance, Operator
from ...operators.conv import FFTConvolution, KernelFn
from ...problem import InverseProblem
from ...registry import register
from ...solve.curriculum import Curriculum
from ..base import Instance
from .data import BlurDataGenerator
from .phantoms import render
from .psf import disk_psf, gaussian_psf, make_psf, motion_psf
from .scenes import DeconvolutionScenes
from .wiener import wiener, wiener_discrepancy

#: inversion-operator discretization tag (differs from the data generator's, see ``fidelity_tag``)
OPERATOR_TAG = "blur-1x-float32"


@dataclass
class DeconvolutionConfig:
    """Configuration of the :class:`Deconvolution` instance (all numbers are config fields).

    Physics: ``n`` × ``n`` pixels on ``[0, extent]²``; ``psf`` ∈ {gaussian (``psf_sigma``),
    motion (``motion_length``, ``motion_angle`` degrees), disk (``disk_radius``)} in physical units;
    ``noise`` ∈ {gaussian (relative ``noise_std``), poisson (``peak_counts``,
    ``background_counts``)}; data simulated on a ``supersample`` × finer grid.
    Prior / solver: neural field (``hidden``, ``depth``, ``skip_at``, ``n_octaves``,
    ``activation``), ``head`` ∈ {softplus, bounded}, ``data_loss`` ∈ {auto, mse, poisson_nll},
    isotropic ``tv`` (``tv_eps``), ``l1``, two-stage curriculum (``steps``, ``lr``, ``lr_decay``,
    ``anneal_fraction``). Baseline settings are prefixed ``grid_``, ``dd_``, ``splat_``,
    ``admm_``, ``wiener_``.
    """

    n: int = 64
    extent: float = 1.0
    scene: str = "phantom"
    psf: str = "gaussian"
    psf_sigma: float = 0.02
    motion_length: float = 0.1
    motion_angle: float = 30.0
    disk_radius: float = 0.04
    noise: str = "gaussian"
    noise_std: float = 0.01
    peak_counts: float = 200.0
    background_counts: float = 1.0
    supersample: int = 2
    dot_cells: float = 0.7
    head: str = "softplus"
    init_value: float = 0.05
    data_loss: str = "auto"
    tv: float = 1e-4
    tv_eps: float = 1e-3
    l1: float = 0.0
    hidden: int = 128
    depth: int = 4
    skip_at: int = 2
    n_octaves: int = 7
    activation: str = "tanh"
    steps: tuple[int, int] = (400, 800)
    lr: float = 2e-2
    lr_decay: float = 0.5
    anneal_fraction: float = 1.0
    grid_lr: float = 5e-2
    grid_l2: float = 0.0
    dd_lr: float = 5e-3
    dd_width: int = 64
    dd_stages: int = 5
    splat_lr: float = 3e-2
    splat_primitives: int = 64
    splat_max_primitives: int = 128
    admm_mu: float = 0.1
    admm_l1: float = 1e-3
    admm_lr: float = 2e-2
    admm_inner: int = 20
    admm_outer: int = 60
    admm_tol: float = 1e-3
    admm_adaptive: bool = True
    wiener_snr: float = 0.0  # <= 0: chosen by the discrepancy principle
    wiener_tau: float = 1.0  # discrepancy factor (residual RMS <= tau * noise level)


@register("instance", "deconvolution")
class Deconvolution(Instance):
    """2-D image deblurring instance (see module docstring)."""

    name = "deconvolution"
    Config = DeconvolutionConfig
    description = "2-D image deblurring (Gaussian / motion / disk PSF; Gaussian or Poisson noise)"

    # ---- physics ------------------------------------------------------------------------
    def domain(self) -> Domain:
        c = self.cfg
        return Domain((c.n, c.n), ((0.0, c.extent), (0.0, c.extent)), axes=("x", "y"))

    def psf_fn(self) -> KernelFn:
        c = self.cfg
        return make_psf(c.psf, c.psf_sigma, c.motion_length, c.motion_angle, c.disk_radius)

    def blur(self, domain: Domain | None = None) -> FFTConvolution:
        """Blur operator in image units (no count scaling)."""
        return FFTConvolution(self.psf_fn(), domain or self.domain(), field="x", periodic=False)

    def operator(self, domain: Domain | None = None) -> Operator:
        """Inversion operator: blur, times ``peak_counts`` plus background for Poisson data."""
        c = self.cfg
        op: Operator = self.blur(domain)
        if c.noise == "poisson":
            op = Nuisance(
                op,
                gain=False,
                offset=False,
                init_gain=c.peak_counts,
                init_offset=c.background_counts,
            )
        op.fidelity_tag = OPERATOR_TAG
        return op

    def scene_generator(self) -> SceneGenerator:
        return DeconvolutionScenes(self.domain(), dot_cells=self.cfg.dot_cells)

    def data_generator(self) -> DataGenerator:
        c = self.cfg
        return BlurDataGenerator(
            self.blur(self.domain().refine(c.supersample)),
            noise=c.noise,
            noise_std=c.noise_std,
            peak_counts=c.peak_counts,
            background_counts=c.background_counts,
            supersample=c.supersample,
            fidelity_tag="blur-2x-float64",
        )

    def build_problem_measurement_shape(self, field_shape):
        return tuple(field_shape)

    def measurement_image(self, measurement: Measurement) -> torch.Tensor:
        """Measurement in image units (counts → intensity for Poisson data)."""
        c = self.cfg
        if c.noise == "poisson":
            return (measurement.data - c.background_counts) / c.peak_counts
        return measurement.data

    # ---- prior / objective --------------------------------------------------------------
    def heads(self) -> Heads:
        c = self.cfg
        if c.head == "softplus":
            return Heads({"x": Softplus(init_value=c.init_value)})
        if c.head == "bounded":
            return Heads({"x": Bounded(0.0, 1.0, init_value=c.init_value)})
        raise ConfigError(f"head must be 'softplus' or 'bounded', got {c.head!r}")

    def field(self) -> NeuralField:
        c = self.cfg
        return NeuralField(
            2,
            self.heads(),
            hidden=c.hidden,
            depth=c.depth,
            skip_at=c.skip_at,
            n_octaves=c.n_octaves,
            activation=c.activation,
        )

    def losses(self, l2: float = 0.0) -> LossSet:
        c = self.cfg
        kind = c.data_loss
        if kind == "auto":
            kind = "poisson_nll" if c.noise == "poisson" else "mse"
        if kind == "mse":
            data, w = MSE(), 1.0
        elif kind == "poisson_nll":
            if c.noise != "poisson":
                raise ConfigError("poisson_nll needs noise='poisson' (count data)")
            data, w = PoissonNLL(), 1.0 / c.peak_counts  # per-count NLL -> image units
        else:
            raise ConfigError(f"data_loss must be auto | mse | poisson_nll, got {kind!r}")
        terms = {"data": data, "tv": TV("x", isotropic=True, eps=c.tv_eps), "l1": L1("x")}
        weights = {"data": w, "tv": c.tv, "l1": c.l1}
        if l2 > 0:
            terms["l2"] = Tikhonov("x")
            weights["l2"] = l2
        return LossSet(terms, weights=weights)

    def default_curriculum(self) -> Curriculum:
        c = self.cfg
        return Curriculum.multiscale(
            (c.n, c.n),
            n_stages=2,
            steps=tuple(c.steps),
            lr=c.lr,
            lr_decay=c.lr_decay,
            anneal_fraction=c.anneal_fraction,
        )

    def build_problem(
        self, measurement: Measurement, losses: LossSet | None = None
    ) -> InverseProblem:
        return InverseProblem(
            self.domain(),
            self.field(),
            self.operator(),
            losses or self.losses(),
            measurement,
            curriculum=self.default_curriculum(),
            name="deconvolution",
            meta={"scene": self.cfg.scene, "noise": self.cfg.noise, "psf": self.cfg.psf},
        )

    def metrics(self) -> dict[str, Callable]:
        return {"psnr": psnr, "ssim": ssim, "mse": mse}

    # ---- references & baselines -------------------------------------------------------
    def noise_level(self, measurement: Measurement) -> float:
        """Noise std in image units (known Gaussian std, or ``√λ / peak`` for Poisson counts)."""
        c = self.cfg
        if c.noise == "poisson":
            return float(torch.sqrt(measurement.data.clamp_min(1.0).mean())) / c.peak_counts
        ns = measurement.noise_std
        if ns is not None:
            return float(torch.as_tensor(ns).mean())
        return 0.01 * float(measurement.data.abs().max())

    def wiener_reconstruction(self, measurement: Measurement) -> tuple[torch.Tensor, float]:
        """Closed-form Wiener reconstruction (image units, ≥ 0) and the SNR used.

        ``wiener_snr > 0`` fixes the SNR; otherwise it is chosen by Morozov's discrepancy
        principle with factor ``wiener_tau`` (:func:`wiener_discrepancy`).
        """
        c = self.cfg
        img = self.measurement_image(measurement)
        blur = self.blur()
        if c.wiener_snr > 0:
            return wiener(img, blur, c.wiener_snr), float(c.wiener_snr)
        return wiener_discrepancy(img, blur, self.noise_level(measurement), tau=c.wiener_tau)

    def wiener(self, measurement: Measurement) -> torch.Tensor:
        """Closed-form Wiener reconstruction of ``measurement`` (image units, clipped ≥ 0)."""
        return self.wiener_reconstruction(measurement)[0]

    def baselines(self) -> dict[str, Callable[[Measurement], tuple[InverseProblem, Curriculum]]]:
        c = self.cfg

        def grid(m: Measurement):
            prob = self.build_problem(m, self.losses(l2=c.grid_l2))
            return baseline_problem(prob, "grid", lr=c.grid_lr)

        def deep_decoder(m: Measurement):
            return baseline_problem(
                self.build_problem(m),
                "deep_decoder",
                lr=c.dd_lr,
                width=c.dd_width,
                n_stages=c.dd_stages,
            )

        def gaussian_splat(m: Measurement):
            return baseline_problem(
                self.build_problem(m),
                "gaussian_splat",
                lr=c.splat_lr,
                n_primitives=c.splat_primitives,
                max_primitives=c.splat_max_primitives,
            )

        def admm(m: Measurement):
            return baseline_problem(
                self.build_problem(m),
                "admm",
                admm={
                    "mu": c.admm_mu,
                    "l1": c.admm_l1,
                    "lr": c.admm_lr,
                    "n_inner": c.admm_inner,
                    "max_outer": c.admm_outer,
                    "tol": c.admm_tol,
                    "adaptive_mu": c.admm_adaptive,
                },
            )

        def wiener_baseline(m: Measurement):
            x0, snr = self.wiener_reconstruction(m)
            blur = self.blur()

            def reconstruct(obs: Measurement, dom: Domain) -> torch.Tensor:
                return wiener(self.measurement_image(obs), blur.at_resolution(dom.shape), snr)

            shape = (c.n, c.n)
            field = GridField(shape, Heads({"x": Identity()}), init=x0[..., None])
            cur = Curriculum.single(shape, steps=1, lr=0.0, anneal=False)
            prob = InverseProblem(
                self.domain(),
                field,
                self.operator(),
                self.losses(),
                m,
                curriculum=cur,
                name="deconvolution-wiener",
                meta={"solver": "direct", "reconstruct": reconstruct, "baseline": "wiener"},
            )
            return prob, cur

        return {
            "grid": grid,
            "deep_decoder": deep_decoder,
            "gaussian_splat": gaussian_splat,
            "admm": admm,
            "wiener": wiener_baseline,
        }


def make_problem(
    n: int = 64, seed: int = 0, scene: str | None = None, **cfg
) -> tuple[InverseProblem, dict[str, torch.Tensor], Measurement]:
    """Convenience: ``(problem, gt, measurement)`` for docs and tests."""
    inst = Deconvolution(n=n, **({"scene": scene} if scene else {}), **cfg)
    gt, meas = inst.make_measurement(seed)
    return inst.build_problem(meas), gt, meas


def run(cfg: DeconvolutionConfig | dict | None = None, seed: int = 0, **kw):
    """End-to-end demo (generate → invert → evaluate); returns a ``RunOutput``."""
    return Deconvolution(cfg).run(seed=seed, **kw)


METRICS: dict[str, Callable] = {"psnr": psnr, "ssim": ssim, "mse": mse}

__all__ = [
    "METRICS",
    "OPERATOR_TAG",
    "BlurDataGenerator",
    "Deconvolution",
    "DeconvolutionConfig",
    "DeconvolutionScenes",
    "disk_psf",
    "gaussian_psf",
    "make_problem",
    "make_psf",
    "motion_psf",
    "render",
    "run",
    "wiener",
    "wiener_discrepancy",
]
