"""poisson_source — PDE-constrained source recovery for the Poisson equation (elliptic).

Recover a non-negative source ``f`` in ``-κΔu = f`` on the unit square with homogeneous Dirichlet
conditions from noisy observations of ``u`` on a sparse random pixel subset (``obs_fraction``,
e.g. 10 %) or on a boundary strip. The forward model is the differentiable spectral solver
:class:`PoissonOperator` (DST-II via ``torch.fft``) returning the *full* ``u`` grid; observations
are selected by the :class:`~nefi.Measurement` mask, so the data term is a masked mean. Coarse
curriculum stages use mask-aware downsampling (:func:`masked_downsample`). Data are generated by a
5-point finite-difference solver on a 2× finer grid in float64 (scipy sparse direct solve), then
area-averaged (``fidelity_tag="poisson-fd-2x-float64"``, inverse-crime guard).

Prior: neural field with a ``Softplus`` (non-negative) or ``Identity`` head, ℓ1 sparsity and
isotropic TV. Baselines: ``grid`` and ``deep_decoder``.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

import torch

from ...baselines import baseline_problem
from ...bench.base import DataGenerator, SceneGenerator
from ...domain import Domain
from ...errors import ConfigError
from ...fields import Heads, Identity, NeuralField, Softplus
from ...losses import L1, MSE, TV, LossSet, RelativeMSE
from ...measurement import Measurement
from ...metrics.basic import mse, psnr, relative_error
from ...problem import InverseProblem
from ...registry import register
from ...solve.curriculum import Curriculum
from ..base import Instance
from .data import OBS_MODES, PoissonDataGenerator, masked_downsample, observation_mask
from .operator import (
    FDPoissonOperator,
    PoissonOperator,
    dst1,
    dst2,
    fd_poisson_solve,
    idst1,
    idst2,
)
from .scenes import SourceScenes


@dataclass
class PoissonSourceConfig:
    """Configuration of the :class:`PoissonSource` instance (all numbers are config fields).

    Physics: ``n × n`` grid on ``[0, extent]²``, conductivity ``κ``, inversion ``spectrum`` ∈
    {continuous, fd}; observations ``obs_mode`` ∈ {random (``obs_fraction``), boundary
    (``boundary_width`` cells), full} with relative Gaussian ``noise_std``; data simulated by
    finite differences on a ``supersample``× grid. Prior / solver: neural field (``hidden``,
    ``depth``, ``skip_at``, ``n_octaves``, ``activation``), ``head`` ∈ {softplus, identity},
    ``data_loss`` ∈ {relative_mse (scale-free masked MSE), mse}, ``l1``, isotropic ``tv``
    (``tv_eps``), two-stage curriculum (``steps``, ``lr``, ``lr_decay``, ``anneal_fraction``).
    Baselines: ``grid_lr``, ``dd_*``.
    """

    n: int = 64
    extent: float = 1.0
    conductivity: float = 1.0
    spectrum: str = "continuous"
    scene: str = "blobs"
    point_cells: float = 0.8
    obs_mode: str = "random"
    obs_fraction: float = 0.1
    boundary_width: int = 3
    noise_std: float = 0.01
    supersample: int = 2
    head: str = "softplus"
    init_value: float = 0.05
    data_loss: str = "relative_mse"
    l1: float = 1e-3
    tv: float = 1e-4
    tv_eps: float = 1e-3
    hidden: int = 128
    depth: int = 4
    skip_at: int = 2
    n_octaves: int = 6
    activation: str = "tanh"
    steps: tuple[int, int] = (1000, 2000)
    lr: float = 1e-2
    lr_decay: float = 0.5
    anneal_fraction: float = 1.0
    grid_lr: float = 5e-2
    dd_lr: float = 5e-3
    dd_width: int = 64
    dd_stages: int = 5


@register("instance", "poisson_source")
class PoissonSource(Instance):
    """Elliptic source-recovery instance (see module docstring)."""

    name = "poisson_source"
    Config = PoissonSourceConfig
    description = "Poisson-equation source recovery from sparse / boundary potential observations"

    def domain(self) -> Domain:
        c = self.cfg
        return Domain((c.n, c.n), ((0.0, c.extent), (0.0, c.extent)), axes=("x", "y"))

    def operator(self, domain: Domain | None = None) -> PoissonOperator:
        c = self.cfg
        return PoissonOperator(domain or self.domain(), "f", c.conductivity, c.spectrum)

    def scene_generator(self) -> SceneGenerator:
        return SourceScenes(self.domain(), point_cells=self.cfg.point_cells)

    def data_generator(self) -> DataGenerator:
        c = self.cfg
        if c.obs_mode not in OBS_MODES:
            raise ConfigError(f"obs_mode must be one of {OBS_MODES}, got {c.obs_mode!r}")
        fine = FDPoissonOperator(self.domain().refine(c.supersample), "f", c.conductivity)
        return PoissonDataGenerator(
            fine,
            noise_std=c.noise_std,
            obs_mode=c.obs_mode,
            obs_fraction=c.obs_fraction,
            boundary_width=c.boundary_width,
            supersample=c.supersample,
            fidelity_tag="poisson-fd-2x-float64",
        )

    def build_problem_measurement_shape(self, field_shape):
        return tuple(field_shape)

    def heads(self) -> Heads:
        c = self.cfg
        if c.head == "softplus":
            return Heads({"f": Softplus(init_value=c.init_value)})
        if c.head == "identity":
            return Heads({"f": Identity()})
        raise ConfigError(f"head must be 'softplus' or 'identity', got {c.head!r}")

    def field(self) -> NeuralField:
        c = self.cfg
        return NeuralField(
            2,
            self.heads(),
            hidden=c.hidden,
            depth=c.depth,
            skip_at=c.skip_at,
            n_octaves=c.n_octaves,
            activation=c.activation,
        )

    def losses(self) -> LossSet:
        c = self.cfg
        if c.data_loss == "relative_mse":
            data = RelativeMSE()
        elif c.data_loss == "mse":
            data = MSE()
        else:
            raise ConfigError(f"data_loss must be 'relative_mse' or 'mse', got {c.data_loss!r}")
        return LossSet(
            {"data": data, "l1": L1("f"), "tv": TV("f", isotropic=True, eps=c.tv_eps)},
            weights={"data": 1.0, "l1": c.l1, "tv": c.tv},
        )

    def default_curriculum(self) -> Curriculum:
        c = self.cfg
        return Curriculum.multiscale(
            (c.n, c.n),
            n_stages=2,
            steps=tuple(c.steps),
            lr=c.lr,
            lr_decay=c.lr_decay,
            anneal_fraction=c.anneal_fraction,
        )

    def build_problem(self, measurement: Measurement) -> InverseProblem:
        return InverseProblem(
            self.domain(),
            self.field(),
            self.operator(),
            self.losses(),
            measurement,
            curriculum=self.default_curriculum(),
            downsample_obs=masked_downsample,
            name="poisson_source",
            meta={"scene": self.cfg.scene, "obs_mode": self.cfg.obs_mode},
        )

    def metrics(self) -> dict[str, Callable]:
        return {"psnr": psnr, "mse": mse, "relative_error": relative_error}

    def baselines(self) -> dict[str, Callable[[Measurement], tuple[InverseProblem, Curriculum]]]:
        c = self.cfg

        def grid(m: Measurement):
            return baseline_problem(self.build_problem(m), "grid", lr=c.grid_lr)

        def deep_decoder(m: Measurement):
            return baseline_problem(
                self.build_problem(m),
                "deep_decoder",
                lr=c.dd_lr,
                width=c.dd_width,
                n_stages=c.dd_stages,
            )

        return {"grid": grid, "deep_decoder": deep_decoder}


def make_problem(
    n: int = 64, seed: int = 0, scene: str | None = None, **cfg
) -> tuple[InverseProblem, dict[str, torch.Tensor], Measurement]:
    """Convenience: ``(problem, gt, measurement)`` for docs and tests."""
    inst = PoissonSource(n=n, **({"scene": scene} if scene else {}), **cfg)
    gt, meas = inst.make_measurement(seed)
    return inst.build_problem(meas), gt, meas


def run(cfg: PoissonSourceConfig | dict | None = None, seed: int = 0, **kw):
    """End-to-end demo (generate → invert → evaluate); returns a ``RunOutput``."""
    return PoissonSource(cfg).run(seed=seed, **kw)


METRICS: dict[str, Callable] = {"psnr": psnr, "mse": mse, "relative_error": relative_error}

__all__ = [
    "METRICS",
    "OBS_MODES",
    "FDPoissonOperator",
    "PoissonDataGenerator",
    "PoissonOperator",
    "PoissonSource",
    "PoissonSourceConfig",
    "SourceScenes",
    "dst1",
    "dst2",
    "fd_poisson_solve",
    "idst1",
    "idst2",
    "make_problem",
    "masked_downsample",
    "observation_mask",
    "run",
]
