"""Generate the API reference from the package docstrings.

Usage::

    python scripts/gen_api_docs.py [--out docs/api.md] [--package nefi]

Writes ``docs/api.md`` (an index of every module) and one page per subpackage under ``docs/api/``
(``core.md`` for the top-level modules, ``fields.md``, ``operators.md``, ...), so each file stays
small as the package grows. Every public module is imported; each public class / function is
documented in the module that *defines* it (re-exports are not repeated) with its signature and the
first paragraph of its docstring; classes list their public methods and properties. Private
modules (``_name``) and private names are skipped. The output is deterministic, so it can be
committed and diffed; ``make docs`` regenerates it.
"""

from __future__ import annotations

import argparse
import importlib
import inspect
import pkgutil
import re
import sys
from pathlib import Path
from types import ModuleType

INDEX_HEADER = """# API reference

Generated by `scripts/gen_api_docs.py` from the docstrings (`make docs` regenerates it) — do not
edit by hand. Each subpackage has its own page (the sections below); objects are documented in the
module that defines them, and `nefi/__init__.py` re-exports the most common ones
(`nefi.InverseProblem`, `nefi.Solver`, `nefi.invert`, `nefi.from_forward`, ...). See
[DESIGN.md](DESIGN.md) for the contracts and [paper_mapping.md](paper_mapping.md) for the paper →
code map.

"""

PAGE_HEADER = """# API — `{title}`

Generated by `scripts/gen_api_docs.py` — do not edit by hand. [Index](../api.md)

"""


def first_paragraph(doc: str | None) -> str:
    """First paragraph of a docstring, joined into one line."""
    if not doc:
        return ""
    text = inspect.cleandoc(doc).split("\n\n", 1)[0]
    return " ".join(line.strip() for line in text.splitlines()).strip()


_ABBREV = ("App", "Eq", "Eqs", "Tab", "Fig", "Prop", "Cor", "Sec", "e.g", "i.e", "al", "vs", "cf")


def first_line(doc: str | None) -> str:
    """First sentence of the first paragraph (paper abbreviations such as "App." kept)."""
    text = first_paragraph(doc)
    for m in re.finditer(r"\.(\s+)(?=[A-Z(`*])", text):
        head = text[: m.start()]
        if not any(head.endswith(a) for a in _ABBREV) and not re.search(r"\b[A-Z]$", head):
            return head + "."
    return text


def _fmt_param(p: inspect.Parameter) -> str:
    kinds = {p.VAR_POSITIONAL: "*", p.VAR_KEYWORD: "**"}
    text = kinds.get(p.kind, "") + p.name
    if p.annotation is not p.empty:
        ann = (
            p.annotation
            if isinstance(p.annotation, str)
            else inspect.formatannotation(p.annotation)
        )
        text += f": {ann}"
    if p.default is not p.empty:
        d = repr(p.default)
        d = re.sub(r"<([\w.]+) object at 0x[0-9a-f]+>", r"\1", d)
        d = re.sub(r"<function ([\w.<>]+) at 0x[0-9a-f]+>", r"\1", d)
        text += f" = {d}" if p.annotation is not p.empty else f"={d}"
    return text


def signature(obj: object, limit: int = 160) -> str:
    try:
        sig = inspect.signature(obj)
    except (TypeError, ValueError):
        return "(...)"
    params, seen_kwonly = [], False
    for p in sig.parameters.values():
        if p.kind == p.KEYWORD_ONLY and not seen_kwonly:
            params.append("*")
            seen_kwonly = True
        if p.kind == p.VAR_POSITIONAL:
            seen_kwonly = True
        params.append(_fmt_param(p))
    text = "(" + ", ".join(params) + ")"
    ret = sig.return_annotation
    if ret is not sig.empty and ret not in ("None", None):
        text += f" -> {ret if isinstance(ret, str) else inspect.formatannotation(ret)}"
    return text if len(text) <= limit else text[: limit - 3] + "..."


def iter_modules(package: str) -> list[ModuleType]:
    root = importlib.import_module(package)
    mods = [root]
    for info in pkgutil.walk_packages(root.__path__, prefix=f"{package}."):
        name = info.name
        if any(part.startswith("_") for part in name.split(".")[1:]):
            continue
        try:
            mods.append(importlib.import_module(name))
        except Exception as e:  # optional dependency missing, broken module under construction
            print(f"skip {name}: {type(e).__name__}: {e}", file=sys.stderr)
    return sorted(mods, key=lambda m: m.__name__)


def public_members(mod: ModuleType) -> list[tuple[str, object]]:
    names = getattr(mod, "__all__", None)
    if names is None:
        names = [n for n in vars(mod) if not n.startswith("_")]
    out = []
    for n in names:
        obj = getattr(mod, n, None)
        if obj is None or not (inspect.isclass(obj) or inspect.isfunction(obj)):
            continue
        if getattr(obj, "__module__", None) != mod.__name__:
            continue  # documented where it is defined
        out.append((n, obj))
    return sorted(out, key=lambda t: (not inspect.isclass(t[1]), t[0].lower()))


def class_members(cls: type) -> list[str]:
    lines = []
    for name, member in sorted(vars(cls).items()):
        if name.startswith("_"):
            continue
        if isinstance(member, property):
            lines.append(f"  - `{name}` (property) — {first_line(member.__doc__)}".rstrip(" —"))
        elif inspect.isfunction(member) or isinstance(member, staticmethod | classmethod):
            fn = member.__func__ if isinstance(member, staticmethod | classmethod) else member
            lines.append(f"  - `{name}{signature(fn)}` — {first_line(fn.__doc__)}".rstrip(" —"))
    return lines


def group_of(modname: str, package: str) -> str:
    parts = modname.split(".")
    if len(parts) == 1:
        return "core"
    sub = importlib.import_module(".".join(parts[:2]))
    return parts[1] if hasattr(sub, "__path__") else "core"


def render_module(m: ModuleType) -> str:
    parts = [f"## `{m.__name__}`\n"]
    doc = first_paragraph(m.__doc__)
    if doc:
        parts.append(doc + "\n")
    for name, obj in public_members(m):
        kind = "class" if inspect.isclass(obj) else "def"
        parts.append(f"### `{kind} {name}{signature(obj)}`\n")
        text = first_paragraph(obj.__doc__)
        if text:
            parts.append(text + "\n")
        if inspect.isclass(obj):
            extra = class_members(obj)
            if extra:
                parts.append("\n".join(extra) + "\n")
    return "\n".join(parts)


def render(package: str) -> dict[str, str]:
    """``{relative path: markdown}`` for the index and every group page."""
    mods = iter_modules(package)
    groups: dict[str, list[ModuleType]] = {}
    for m in mods:
        groups.setdefault(group_of(m.__name__, package), []).append(m)
    pages: dict[str, str] = {}
    index = [INDEX_HEADER]
    for g in sorted(groups, key=lambda k: (k != "core", k)):
        title = package if g == "core" else f"{package}.{g}"
        index.append(f"## [{title}](api/{g}.md)\n")
        body = [PAGE_HEADER.format(title=title)]
        for m in groups[g]:
            anchor = m.__name__.replace(".", "")
            index.append(f"- [`{m.__name__}`](api/{g}.md#{anchor}) — {first_line(m.__doc__)}")
            body.append(render_module(m))
        index.append("")
        pages[f"api/{g}.md"] = "\n".join(body).rstrip() + "\n"
    pages["api.md"] = "\n".join(index).rstrip() + "\n"
    return pages


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default="docs/api.md", help="index path; pages go next to it in api/")
    ap.add_argument("--package", default="nefi")
    args = ap.parse_args()
    out = Path(args.out)
    root = out.parent
    pages = render(args.package)
    (root / "api").mkdir(parents=True, exist_ok=True)
    for old in (root / "api").glob("*.md"):
        if f"api/{old.name}" not in pages:
            old.unlink()
    for rel, text in pages.items():
        path = out if rel == "api.md" else root / rel
        path.write_text(text)
    sizes = ", ".join(f"{rel} {len(t) / 1024:.0f} kB" for rel, t in sorted(pages.items()))
    print(f"wrote {len(pages)} files: {sizes}")


if __name__ == "__main__":
    main()
